Update prod-cd.yml

diff --git a/.github/workflows/prod-cd.yml b/.github/workflows/prod-cd.yml
--- a/.github/workflows/prod-cd.yml
+++ b/.github/workflows/prod-cd.yml
@@ -5,7 +5,6 @@ on:
 
 jobs:
   check_release_job:
-    if: startsWith(github.ref, 'refs/tags/')
     runs-on: ubuntu-latest
     permissions:
       contents: read
@@ -13,6 +12,11 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
+
+      - name: check for a tag
+        if: startsWith(github.ref, 'refs/heads/')
+          echo "Deployment failure. This is a PROD CD you can only proceed using released tags for successful deployment"
+          exit 1
         
       - name: get releases
         run: |
@@ -25,15 +29,6 @@ jobs:
         run: |
           echo "CD is complete"
 
-  build_on_branch:
-    runs-on: ubuntu-latest
-    if: startsWith(github.ref, 'refs/heads/')
-
-    steps:
-    - name: Check out code
-      uses: actions/checkout@v2
-
-    - name: failure message
-      run: echo "Deployment failure. This is a PROD CD you can only proceed using released tags for successful deployment"
+  
 
 
